var data = [
	"CHAN Ka Ki, Karen",
	"CHAN Kam Chung, Tommy",
	"CHAN Po Wah, Kepler",
	"CHAN Yuet Nam, Nancy",
	"CHAU Kai Yeung, Oliver",
	"CHAU Wai Lung, Alex",
	"CHEN Yi Chen, Luna",
	"CHEN Sze Yuen, Tom",
	"CHENG Wai Sim, Joan",
	"CHEONG Chun Nok",
	"CHIU Wing Cheung, Tony",
	"CHOW Man Sang, Sam",
	"CHOW Tsz Chun",
	"CHU Carmen",
	"CHU Ka Hei, Jay",
	"CHU Ka Sin, Kuro",
	"DUAN Lian",
	"FONG Ka Ho, Brad",
	"HO Ding Kwok, Clement",
	"IP Chun Long, Gabe",
	"KWOK, Wilson",
	"KONG Shu-Wa, Justin",
	"LAI Kam Kuen, William",
	"LAU Sui Wah",
	"LEE King Hong, Raman",
	"LEUNG Chak Fung, Jacky",
	"LEUNG Ka Wang, Chris",
	"LEUNG Sui Ying, Judy",
	"LEUNG Wai Yat, Jason",
	"LI Cheuk-Nam, Bernadette",
	"LO Hau Yan, Kathy",
	"LO Mei Chee, Maisy",
	"LO Yim Fun, Louise",
	"LUK Siu-Chun, Brian",
	"MA Lok Man, Bosco",
	"MAK Hoi Lam, Natalie",
	"MAK Tung Wing",
	"MO Man Ching, Amanda",
	"NG Tsz Hin",
	"NGUYEN Quang Hong",
	"POON Ka Man Carman",
	"POON Shing Tat, Perry",
	"SHIRAHIGE, Makito",
	"SIN Pak Yin, Eddy",
	"SZETO Man Fung, Jacob",
	"TAI Sai Keung, Sunny",
	"TANG Cheuk Wing, Cherry",
	"TANG Sze Wai, Ray",
	"TANG Tao I",
	"TSANG Yik, Ricky",
	"TSANG Yiu Bong, Eric",
	"WANG Wan Shu, Zoe",
	"WONG Corey Jonathan",
	"WONG Ka Man, Carmen",
	"WONG Nga Yu, Joyce",
	"WONG Wai Shing, Thomas",
	"YEUNG Ka Lai, Agnes",
	"YEUNG Ka Sui, Iris",
	"YEUNG Sheung Chi, Henry",
	"YIP Cheuk Ki, Tony",
	"YU Kent",
	"ZHANG Zi Liang, Eames",
	"ZHAO Tian Yu",
];
